# Перечень таблиц

In [1]:
import pandas as pd

from warnings import simplefilter
simplefilter('ignore')

Ниже приведен перечень таблиц, созданных и используемых в рамках проекта.\
Все таблицы должны находится в папке `./data` относительно данного файла.\
Поскольку на Github есть лимит на размер загружаемых файлов, \
таблицы загружены отдельно в папку https://disk.yandex.ru/d/UowZbTRZCUfnJg .

Около половины перечисленных таблиц объединяются в общую в файле [01_main.ipynb](./01_creating_tables/01_main.ipynb)\
Префикс названия таблицы содержит в себе отсылку к доменному имени сайта, с которого она была получена.\
Окончание `_prepared` означает, что данные таблицы преобразованы для последующего объединения в общую таблицу.

## who_life_expectancy_all.csv

**Описание содержимого:** данные о странах и ожидаемой продолжительности жизни в них.

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/life-expectancy-at-birth-(years)

In [93]:
who_life_expectancy_all_data = pd.read_csv('./data/who_life_expectancy_all.csv')

who_life_expectancy_all_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,LSO,Lesotho,Year,2020,...,NaN,NaN,50.77,NaN,53.15,51.9 [50.8-53.2],NaN,NaN,EN,2024-08-02 00:00:00
1,WHOSIS_000001,Life expectancy at birth (years),text,AFR,Africa,Country,CAF,Central African Republic,Year,2020,...,NaN,NaN,51.90,NaN,54.10,53.1 [51.9-54.1],NaN,NaN,EN,2024-08-02 00:00:00

## regions_and_locations.csv

**Описание содержимого:** содержит коды и названия регионов и стран.

**Источник данных:** создана из таблицы `who_life_expectancy_all.csv`

In [94]:
regions_and_locations_data = pd.read_csv(
    './data/regions_and_locations.csv'
)

regions_and_locations_data.head()

  ParentLocationCode ParentLocation SpatialDimValueCode      Location
0                AFR         Africa                 AGO        Angola
1                AFR         Africa                 BDI       Burundi
2                AFR         Africa                 BEN         Benin
3                AFR         Africa                 BFA  Burkina Faso
4                AFR         Africa                 BWA      Botswana

## who_adult_mortality.csv

**Описание содержимого:** коэффициент смертности среди взрослого населения \
(вероятность смерти в возрасте от 15 до 60 лет на 1000 человек населения) 

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/adult-mortality-rate-(probability-of-dying-between-15-and-60-years-per-1000-population)

In [95]:
who_adult_mortality_data = pd.read_csv('./data/who_adult_mortality.csv')

who_adult_mortality_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHOSIS_000004,Adult mortality rate (probability of dying bet...,numeric,AMR,Americas,Country,PAN,Panama,Year,2020,...,NaN,NaN,NaN,NaN,NaN,101,NaN,NaN,EN,2024-10-31 00:00:00
1,WHOSIS_000004,Adult mortality rate (probability of dying bet...,numeric,EMR,Eastern Mediterranean,Country,IRN,Iran (Islamic Republic of),Year,2020,...,NaN,NaN,NaN,NaN,NaN,103,NaN,NaN,EN,2024-10-31 00:00:00

## who_child_0_5_mortality.csv

**Описание содержимого:** распределение причин смерти среди детей в возрасте до 5 лет (%)

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/distribution-of-causes-of-death-among-children-aged-5-years-(-)

In [96]:
who_child_0_5_mortality_data = pd.read_csv(
    './data/who_child_0_5_mortality.csv'
)

who_child_0_5_mortality_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,MORT_300,Distribution of causes of death among children...,numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2017,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2018-11-26T21:00:00.000Z
1,MORT_300,Distribution of causes of death among children...,numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2017,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2018-11-26T21:00:00.000Z

## child_0_5_mortality_codes.csv

**Описание содержимого:** описание кодов причин детской смертности до 5 лет.

**Источник данных:** cоставлена из таблицы `who_child_0_5_mortality.csv`

In [97]:
child_0_5_mortality_codes_data = pd.read_csv('./data/child_0_5_mortality_codes.csv')

child_0_5_mortality_codes_data.head()

,WhoCauseCode,Description,CauseCode
0,CHILDCAUSE_CH10,Prematurity,ChildUnder5Mortality10
1,CHILDCAUSE_CH11,Birth asphyxia and birth trauma,ChildUnder5Mortality11
2,CHILDCAUSE_CH12,Sepsis and other infectious conditions of the ...,ChildUnder5Mortality12
3,CHILDCAUSE_CH13,"Other communicable, perinatal and nutritional ...",ChildUnder5Mortality13
4,CHILDCAUSE_CH15,Congenital anomalies,ChildUnder5Mortality15

## who_child_0_5_mortality_prepared.csv

**Описание содержимого:** распределение причин смерти среди детей в возрасте до 5 лет (%).

**Источник данных:** cоздана из таблицы `who_child_0_5_mortality.csv`

In [98]:
who_child_0_5_mortality_prepared_data = pd.read_csv('./data/who_child_0_5_mortality_prepared.csv')

who_child_0_5_mortality_prepared_data.head()

,SpatialDimValueCode,Period,ChildUnder5Mortality2,ChildUnder5Mortality5,ChildUnder5Mortality6,ChildUnder5Mortality7,ChildUnder5Mortality8,ChildUnder5Mortality12,ChildUnder5Mortality3,ChildUnder5Mortality11,ChildUnder5Mortality13,ChildUnder5Mortality17,ChildUnder5Mortality9,ChildUnder5Mortality16,ChildUnder5Mortality15,ChildUnder5Mortality10,ChildUnder5MortalitySum
0,AFG,2000,0.0001,0.086,0.084,0.044,0.002,0.038,0.1200,0.130,0.061,0.039,0.180,0.036,0.036,0.140,0.9961
1,ALB,2000,0.0000,0.003,0.001,0.039,0.000,0.020,0.0290,0.059,0.056,0.100,0.200,0.087,0.200,0.200,0.9940
2,DZA,2000,0.0002,0.004,0.045,0.017,0.000,0.062,0.0820,0.120,0.049,0.053,0.160,0.077,0.110,0.230,1.0092
3,AND,2000,0.0000,0.000,0.000,0.002,0.000,0.000,0.0003,0.000,0.003,0.001,0.005,0.160,0.160,0.660,0.9913
4,AGO,2000,0.0070,0.016,0.011,0.052,0.098,0.029,0.2000,0.095,0.091,0.036,0.210,0.027,0.038,0.087,0.9970

## who_homicides.csv

**Описание содержимого:** оценки уровня убийств (на 100 000 населения).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/estimates-of-rates-of-homicides-per-100-000-population

In [99]:
who_homicides_data = pd.read_csv('./data/who_homicides.csv')

who_homicides_data.head(3)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,VIOLENCE_HOMICIDERATE,Estimates of rates of homicides per 100 000 po...,numeric,WPR,Western Pacific,Country,JPN,Japan,Year,2019,...,NaN,NaN,0.19,NaN,0.23,0.2 [0.2-0.2],NaN,NaN,EN,2021-02-09 00:00:00
1,VIOLENCE_HOMICIDERATE,Estimates of rates of homicides per 100 000 po...,numeric,WPR,Western Pacific,Country,SGP,Singapore,Year,2019,...,NaN,NaN,0.20,NaN,0.32,0.3 [0.2-0.3],NaN,NaN,EN,2021-02-09 00:00:00
2,VIOLENCE_HOMICIDERATE,Estimates of rates of homicides per 100 000 po...,numeric,EMR,Eastern Mediterranean,Country,BHR,Bahrain,Year,2019,...,NaN,NaN,0.16,NaN,0.54,0.3 [0.2-0.5],NaN,NaN,EN,2021-02-09 00:00:00

## who_homicides_prepared.csv

**Описание содержимого:** создана из таблицы `who_homicides.csv`.

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/estimates-of-rates-of-homicides-per-100-000-population

In [100]:
who_homicides_prepared_data = pd.read_csv('./data/who_homicides_prepared.csv')

who_homicides_prepared_data.head(3)

  SpatialDimValueCode  Period  Homicides
0                 JPN    2019       0.21
1                 SGP    2019       0.25
2                 BHR    2019       0.31

## who_maternal_mortality.csv

**Описание содержимого:** коэффициент материнской смертности (на 100 000 живорождений).

**Источник данных:** https://www.who.int/data/gho/gho-redirect-pages/indicator-resources/maternal-mortality-ratio-(per-100-000-live-births)

In [101]:
who_maternal_mortality_data = pd.read_csv('./data/who_maternal_mortality.csv')

who_maternal_mortality_data.head(3)

,IND_ID,IND_CODE,IND_UUID,IND_PER_CODE,DIM_TIME,DIM_TIME_TYPE,DIM_GEO_CODE_M49,DIM_GEO_CODE_TYPE,DIM_PUBLISH_STATE_CODE,IND_NAME,GEO_NAME_SHORT,RATE_PER_100000_N,RATE_PER_100000_NL,RATE_PER_100000_NU
0,AC597B1MDG_0000000026,MDG_0000000026,AC597B1,MDG_0000000026,2003,YEAR,882,COUNTRY,PUBLISHED,Maternal mortality ratio,Samoa,63.63342,32.79250,120.05662
1,AC597B1MDG_0000000026,MDG_0000000026,AC597B1,MDG_0000000026,1992,YEAR,953,WHOREGION,PUBLISHED,Maternal mortality ratio,Africa,952.69319,867.55500,1046.78252
2,AC597B1MDG_0000000026,MDG_0000000026,AC597B1,MDG_0000000026,1985,YEAR,957,WHOREGION,PUBLISHED,Maternal mortality ratio,Eastern Mediterranean,414.44851,347.67278,497.28118

## who_maternal_mortality_prepared.csv

**Описание содержимого:** создана из таблицы `who_maternal_mortality.csv`.

**Источник данных:** https://www.who.int/data/gho/gho-redirect-pages/indicator-resources/maternal-mortality-ratio-(per-100-000-live-births)

In [102]:
who_maternal_mortality_prepared_data = pd.read_csv('./data/who_maternal_mortality_prepared.csv')

who_maternal_mortality_prepared_data.head(3)

   Period    Location  MaternalMortality
0    2003       Samoa           63.63342
1    2019  Montenegro            5.81691
2    2020  Montenegro            6.17443

## who_adult_ncd_mortality.csv

**Описание содержимого:** вероятность (в процентах) смерти в возрасте от 30 до 70 лет от сердечно-сосудистых заболеваний, рака, диабета или хронических респираторных заболеваний.

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/probability-of-dying-between-exact-ages-30-and-70-from-any-of-cardiovascular-disease-cancer-diabetes-or-chronic-respiratory-(-)

In [103]:
who_adult_ncd_mortality_data = pd.read_csv(
    './data/who_adult_ncd_mortality.csv'
)

who_adult_ncd_mortality_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,EUR,Europe,Country,FRA,France,Year,2020,...,NaN,NaN,8.0,NaN,11.8,10.0 [8.0-11.8],NaN,NaN,EN,2024-12-17T21:00:00.000Z
1,NCDMORT3070,Probability (%) of dying between age 30 and ex...,text,AMR,Americas,Country,CAN,Canada,Year,2020,...,NaN,NaN,8.4,NaN,11.7,10.0 [8.4-11.7],NaN,NaN,EN,2024-12-17T21:00:00.000Z

## who_adult_ncd_mortality_prepared.csv

**Описание содержимого:** создана из таблицы `who_adult_ncd_mortality.csv`.

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/probability-of-dying-between-exact-ages-30-and-70-from-any-of-cardiovascular-disease-cancer-diabetes-or-chronic-respiratory-(-)

In [104]:
who_adult_ncd_mortality_prepared_data = \
    pd.read_csv('./data/who_adult_ncd_mortality_prepared.csv')
    
who_adult_ncd_mortality_prepared_data.head()

  SpatialDimValueCode  Period  AdultNcdMortality
0                 FRA    2020               10.0
1                 CAN    2020               10.0
2                 NZL    2020               10.0
3                 PAN    2020               10.1
4                 CRI    2020               10.1

## who_adult_ncd_causes_mortality.csv

**Описание содержимого:** число смертей взрослых, связанных с неинфекционными заболеваниями, разбитые по типу заболевания.

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/number-of-deaths-attributed-to-non-communicable-diseases-by-type-of-disease-and-sex

In [105]:
who_adult_ncd_causes_mortality_data = pd.read_csv('./data/who_adult_ncd_causes_mortality.csv')

who_adult_ncd_causes_mortality_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,SDG_SH_DTH_RNCOM,Number of deaths attributed to non-communicabl...,numeric,EUR,Europe,Country,MNE,Montenegro,Year,2019,...,NaN,NaN,63.92,NaN,145.0,100 [64-145],NaN,NaN,EN,2021-02-08T21:00:00.000Z
1,SDG_SH_DTH_RNCOM,Number of deaths attributed to non-communicabl...,numeric,EUR,Europe,Country,RUS,Russian Federation,Year,2019,...,NaN,NaN,797625.00,NaN,1203905.0,1003695 [797625-1203905],NaN,NaN,EN,2021-02-08T21:00:00.000Z

## adult_ncd_mortality_codes.csv

**Описание содержимого:** таблица с кодами причин смертности взрослых от неинфекционных заболеваний.

**Источник данных:** создана из таблицы `who_adult_ncd_causes_mortality.csv`.

In [106]:
adult_ncd_mortality_codes_data = pd.read_csv('./data/adult_ncd_mortality_codes.csv')

adult_ncd_mortality_codes_data

       WhoCauseCode              Description             CauseCode
0  GHECAUSES_GHE061      Malignant neoplasms  AdultNcdMortality061
1  GHECAUSES_GHE080        Diabetes mellitus  AdultNcdMortality080
2  GHECAUSES_GHE110  Cardiovascular diseases  AdultNcdMortality110
3  GHECAUSES_GHE117     Respiratory diseases  AdultNcdMortality117

## who_adult_ncd_causes_mortality_prepare.csv

**Описание содержимого:** в данной таблице причины смертности взрослых от неинфекционных заболеваний переведены из строк в столбцы.

**Источник данных:** создана из таблицы `who_adult_ncd_causes_mortality.csv`.

In [107]:
who_adult_ncd_causes_mortality_prepare_data = \
    pd.read_csv('./data/who_adult_ncd_causes_mortality_prepare.csv')

who_adult_ncd_causes_mortality_prepare_data.head()

,SpatialDimValueCode,Period,AdultNcdMortality117,AdultNcdMortality110,AdultNcdMortality080,AdultNcdMortality061,AdultNcdMortalitySum
0,MNE,2000,68.0,3269.0,153.0,960.0,4450.0
1,RUS,2000,59915.0,1265019.0,12976.0,323636.0,1661546.0
2,URY,2000,2104.0,10592.0,694.0,7947.0,21337.0
3,BRB,2000,108.0,847.0,232.0,556.0,1743.0
4,MAR,2000,6019.0,71045.0,4161.0,16699.0,97924.0

## who_poisoning_mortality.csv

**Описание содержимого:** уровень смертности от непреднамеренного отравления (на 100 000 населения).

**Источник данных:** https://www.who.int/data/gho/data/themes/topics/indicator-groups/poison-control-and-unintentional-poisoning

In [108]:
who_poisoning_mortality_data = pd.read_csv('./data/who_poisoning_mortality.csv')

who_poisoning_mortality_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,SDGPOISON,Mortality rate attributed to unintentional poi...,numeric,WPR,Western Pacific,Country,BRN,Brunei Darussalam,Year,2019,...,NaN,NaN,0.0005,NaN,0.002,0.0 [0.0-0.0],NaN,NaN,EN,2021-02-08T21:00:00.000Z
1,SDGPOISON,Mortality rate attributed to unintentional poi...,numeric,AMR,Americas,Country,VCT,Saint Vincent and the Grenadines,Year,2019,...,NaN,NaN,0.0030,NaN,0.008,0.0 [0.0-0.0],NaN,NaN,EN,2021-02-08T21:00:00.000Z

## who_poisoning_mortality_prepared.csv

**Описание содержимого:** уровень смертности от непреднамеренного отравления (на 100 000 населения).

**Источник данных:** создана из таблицы `who_poisoning_mortality.csv`

In [109]:
who_poisoning_mortality_prepared_data = \
    pd.read_csv('./data/who_poisoning_mortality_prepared.csv')

who_poisoning_mortality_prepared_data.head()

  SpatialDimValueCode  Period  PoisoningMortality
0                 BRN    2019               0.001
1                 VCT    2019               0.005
2                 SGP    2019               0.019
3                 ISR    2019               0.047
4                 MDV    2019               0.047

## who_suicide_mortality.csv

**Описание содержимого:** общий уровень самоубийств (на 100 000 населения).

**Источник данных:** https://www.who.int/data/gho/data/themes/mental-health/suicide-rates

In [ ]:
who_suicide_mortality_data = pd.read_csv('./data/who_suicide_mortality.csv')

who_suicide_mortality_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,MH_12,Age-standardized suicide rates (per 100 000 po...,numeric,AMR,Americas,Country,BRB,Barbados,Year,2019,...,NaN,NaN,0.22,NaN,0.42,0.3 [0.2-0.4],NaN,NaN,EN,2021-02-08T21:00:00.000Z
1,MH_12,Age-standardized suicide rates (per 100 000 po...,numeric,AMR,Americas,Country,ATG,Antigua and Barbuda,Year,2019,...,NaN,NaN,0.22,NaN,0.45,0.3 [0.2-0.5],NaN,NaN,EN,2021-02-08T21:00:00.000Z

## who_suicide_mortality_prepared.csv

**Описание содержимого:** общий уровень самоубийств (на 100 000 населения).

**Источник данных:** создана из таблицы `who_suicide_mortality.csv`.

In [ ]:
who_suicide_mortality_prepared_data = pd.read_csv(
    './data/who_suicide_mortality_prepared.csv'
)

who_suicide_mortality_prepared_data.head()

  SpatialDimValueCode  Period  SuicideMortality
0                 BRB    2019              0.31
1                 ATG    2019              0.32
2                 GRD    2019              0.64
3                 VCT    2019              1.01
4                 NER    2019             10.15

## who_alcohol.csv

**Описание содержимого:** потребление алкоголя, которое регистрируется в литрах чистого алкоголя \
на душу населения в возрасте 15+ лет.

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/alcohol-recorded-per-capita-(15-)-consumption-(in-litres-of-pure-alcohol)

In [112]:
who_alcohol_data = pd.read_csv('./data/who_alcohol.csv')

who_alcohol_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,AFG,Afghanistan,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2024-08-11T21:00:00.000Z
1,SA_0000001400,"Alcohol, recorded per capita (15+) consumption...",numeric,EMR,Eastern Mediterranean,Country,KWT,Kuwait,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,EN,2024-08-11T21:00:00.000Z

## who_alcohol_prepared.csv

**Описание содержимого:** потребление алкоголя, которое регистрируется в литрах чистого алкоголя \
на душу населения в возрасте 15+ лет.

**Источник данных:** создана из таблицы `who_alcohol.csv`.

In [113]:
who_alcohol_prepared_data = pd.read_csv('./data/who_alcohol_prepared.csv')

who_alcohol_prepared_data.head()

  SpatialDimValueCode  Period  AlcoholСonsumption
0                 AFG    2020               0.009
1                 KWT    2020               0.000
2                 LBY    2020               0.011
3                 MRT    2020               0.000
4                 PAK    2020               0.048

## who_hepatitis_b_immunization.csv

**Описание содержимого:** охват иммунизацией детей в возрасте 1 года против гепатита В (ГепВ3) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/hepatitis-b-(hepb3)-immunization-coverage-among-1-year-olds-(-)

In [114]:
who_hepatitis_b_immunization_data = pd.read_csv(
    './data/who_hepatitis_b_immunization.csv'
)

who_hepatitis_b_immunization_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHS4_117,Hepatitis B (HepB3) immunization coverage amon...,numeric,WPR,Western Pacific,Country,PNG,Papua New Guinea,Year,2020,...,NaN,NaN,NaN,NaN,NaN,40,NaN,NaN,EN,2024-07-11T21:00:00.000Z
1,WHS4_117,Hepatitis B (HepB3) immunization coverage amon...,numeric,AFR,Africa,Country,CAF,Central African Republic,Year,2020,...,NaN,NaN,NaN,NaN,NaN,42,NaN,NaN,EN,2024-07-11T21:00:00.000Z

## who_hepatitis_b_immunization_prepared.csv

**Описание содержимого:** охват иммунизацией детей в возрасте 1 года против гепатита В (ГепВ3) (%).

**Источник данных:** создана из таблицы `who_hepatitis_b_immunization.csv`.

In [115]:
who_hepatitis_b_immunization_prepared_data = pd.read_csv(
    './data/who_hepatitis_b_immunization_prepared.csv'
)

who_hepatitis_b_immunization_prepared_data.head()

  SpatialDimValueCode  Period  HepatitisBImmunization
0                 PNG    2020                    40.0
1                 CAF    2020                    42.0
2                 SOM    2020                    42.0
3                 GIN    2020                    47.0
4                 AGO    2020                    51.0

## who_measles_immunization.csv

**Описание содержимого:** охват первой дозой вакцины, содержащей коревой компонент (MCV1), среди детей в возрасте 1 года (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/measles-containing-vaccine-first-dose-(mcv1)-immunization-coverage-among-1-year-olds-(-)

In [116]:
who_measles_immunization_data = pd.read_csv(
    './data/who_measles_immunization.csv'
)

who_measles_immunization_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHS8_110,Measles-containing-vaccine first-dose (MCV1) i...,numeric,EUR,Europe,Country,MNE,Montenegro,Year,2020,...,NaN,NaN,NaN,NaN,NaN,24,NaN,NaN,EN,2024-07-11T21:00:00.000Z
1,WHS8_110,Measles-containing-vaccine first-dose (MCV1) i...,numeric,AFR,Africa,Country,CAF,Central African Republic,Year,2020,...,NaN,NaN,NaN,NaN,NaN,41,NaN,NaN,EN,2024-07-11T21:00:00.000Z

## who_measles_immunization_prepared.csv

**Описание содержимого:** охват первой дозой вакцины, содержащей коревой компонент (MCV1), среди детей в возрасте 1 года (%).

**Источник данных:** создана из таблицы `who_measles_immunization.csv`.

In [117]:
who_measles_immunization_prepared_data = pd.read_csv(
    './data/who_measles_immunization_prepared.csv'
)

who_measles_immunization_prepared_data.head()

  SpatialDimValueCode  Period  MeaslesImmunization
0                 MNE    2020                 24.0
1                 CAF    2020                 41.0
2                 AGO    2020                 44.0
3                 PNG    2020                 44.0
4                 TCD    2020                 45.0

## who_polio_immunization.csv

**Описание содержимого:** охват иммунизацией от полиомиелита (Pol3) среди детей в возрасте 1 года (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/polio-(pol3)-immunization-coverage-among-1-year-olds-(-)

In [118]:
who_polio_immunization_data = pd.read_csv(
    './data/who_polio_immunization.csv'
)

who_polio_immunization_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHS4_544,Polio (Pol3) immunization coverage among 1-yea...,numeric,WPR,Western Pacific,Country,PNG,Papua New Guinea,Year,2020,...,NaN,NaN,NaN,NaN,NaN,43,NaN,NaN,EN,2024-07-11T21:00:00.000Z
1,WHS4_544,Polio (Pol3) immunization coverage among 1-yea...,numeric,AFR,Africa,Country,CAF,Central African Republic,Year,2020,...,NaN,NaN,NaN,NaN,NaN,46,NaN,NaN,EN,2024-07-11T21:00:00.000Z

## who_polio_immunization_prepared.csv

**Описание содержимого:** охват иммунизацией от полиомиелита (Pol3) среди детей в возрасте 1 года (%).

**Источник данных:** создана из таблицы `who_polio_immunization.csv`.

In [119]:
who_polio_immunization_prepared_data = pd.read_csv(
    './data/who_polio_immunization_prepared.csv'
)

who_polio_immunization_prepared_data.head()

  SpatialDimValueCode  Period  PolioImmunization
0                 PNG    2020               43.0
1                 CAF    2020               46.0
2                 SOM    2020               47.0
3                 GIN    2020               48.0
4                 AGO    2020               51.0

## who_diphtheria_immunization.csv

**Описание содержимого:** охват иммунизацией детей в возрасте 1 года дифтерийно-столбнячным анатоксином и коклюшем (АКДС3) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/diphtheria-tetanus-toxoid-and-pertussis-(dtp3)-immunization-coverage-among-1-year-olds-(-)

In [120]:
who_diphtheria_immunization_data = pd.read_csv(
    './data/who_diphtheria_immunization.csv'
)

who_diphtheria_immunization_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WHS4_100,Diphtheria tetanus toxoid and pertussis (DTP3)...,numeric,WPR,Western Pacific,Country,PNG,Papua New Guinea,Year,2020,...,NaN,NaN,NaN,NaN,NaN,40,NaN,NaN,EN,2024-07-11T21:00:00.000Z
1,WHS4_100,Diphtheria tetanus toxoid and pertussis (DTP3)...,numeric,AFR,Africa,Country,CAF,Central African Republic,Year,2020,...,NaN,NaN,NaN,NaN,NaN,42,NaN,NaN,EN,2024-07-11T21:00:00.000Z

## who_diphtheria_immunization_prepared.csv

**Описание содержимого:** охват иммунизацией детей в возрасте 1 года дифтерийно-столбнячным анатоксином и коклюшем (АКДС3) (%).

**Источник данных:** создана из таблицы `who_diphtheria_immunization.csv`.

In [121]:
who_diphtheria_immunization_prepared_data = pd.read_csv(
    './data/who_diphtheria_immunization_prepared.csv'
)

who_diphtheria_immunization_prepared_data.head()

  SpatialDimValueCode  Period  DiphtheriaImmunization
0                 PNG    2020                    40.0
1                 CAF    2020                    42.0
2                 SOM    2020                    42.0
3                 GIN    2020                    47.0
4                 AGO    2020                    51.0

## who_bmi_adult_underweight.csv

**Описание содержимого:** распространенность недостаточного веса среди взрослых, ИМТ < 18,5 (стандартизированная по возрасту оценка) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-underweight-among-adults-bmi-18-(age-standardized-estimate)-(-)

In [122]:
who_bmi_adult_underweight_data = pd.read_csv(
    './data/who_bmi_adult_underweight.csv'
)

who_bmi_adult_underweight_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_18A,"Prevalence of underweight among adults, BMI < ...",numeric,WPR,Western Pacific,Country,TON,Tonga,Year,2020,...,NaN,NaN,0.091,NaN,0.56,0.3 [0.1-0.6],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_18A,"Prevalence of underweight among adults, BMI < ...",numeric,WPR,Western Pacific,Country,ASM,American Samoa,Year,2020,...,NaN,NaN,0.085,NaN,0.83,0.3 [0.1-0.8],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_adult_underweight_prepared.csv

**Описание содержимого:** распространенность недостаточного веса среди взрослых, ИМТ < 18,5 (стандартизированная по возрасту оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_adult_underweight.csv`.

In [123]:
who_bmi_adult_underweight_prepared_data = pd.read_csv(
    './data/who_bmi_adult_underweight_prepared.csv'
)

who_bmi_adult_underweight_prepared_data.head()

  SpatialDimValueCode  Period  BmiAdultUnderweight
0                 TON    2020                 0.26
1                 ASM    2020                 0.34
2                 WSM    2020                 0.42
3                 NRU    2020                 0.44
4                 TKL    2020                 0.45

## who_bmi_adult_overweight_25.csv

**Описание содержимого:** распространенность избыточного веса среди взрослых, ИМТ >= 25 (стандартизированная по возрасту оценка) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-overweight-among-adults-bmi--25-(age-standardized-estimate)-(-)

In [124]:
who_bmi_adult_overweight_25_data = pd.read_csv(
    './data/who_bmi_adult_overweight_25.csv'
)

who_bmi_adult_overweight_25_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_25A,"Prevalence of overweight among adults, BMI &Gr...",numeric,AFR,Africa,Country,ETH,Ethiopia,Year,2020,...,NaN,NaN,8.72,NaN,11.62,10.1 [8.7-11.6],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_25A,"Prevalence of overweight among adults, BMI &Gr...",numeric,SEAR,South-East Asia,Country,TLS,Timor-Leste,Year,2020,...,NaN,NaN,11.23,NaN,15.10,13.1 [11.2-15.1],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_adult_overweight_25_prepared.csv

**Описание содержимого:** распространенность избыточного веса среди взрослых, ИМТ >= 25 (стандартизированная по возрасту оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_adult_overweight_25.csv`.

In [125]:
who_bmi_adult_overweight_25_prepared_data = pd.read_csv(
    './data/who_bmi_adult_overweight_25_prepared.csv'
)

who_bmi_adult_overweight_25_prepared_data.head()

  SpatialDimValueCode  Period  BmiAdultOverweight25
0                 ETH    2020                 10.12
1                 TLS    2020                 13.08
2                 BDI    2020                 15.42
3                 MDG    2020                 15.76
4                 ERI    2020                 16.02

## who_bmi_adult_overweight_30.csv

**Описание содержимого:** распространенность ожирения среди взрослых, ИМТ >= 30 (стандартизированная по возрасту оценка) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-obesity-among-adults-bmi--30-(age-standardized-estimate)-(-)

In [126]:
who_bmi_adult_overweight_30_data = pd.read_csv(
    './data/who_bmi_adult_overweight_30.csv'
)

who_bmi_adult_overweight_30_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_30A,"Prevalence of obesity among adults, BMI &Great...",numeric,WPR,Western Pacific,Country,VNM,Viet Nam,Year,2020,...,NaN,NaN,1.35,NaN,2.13,1.7 [1.3-2.1],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_30A,"Prevalence of obesity among adults, BMI &Great...",numeric,AFR,Africa,Country,ZMB,Zambia,Year,2020,...,NaN,NaN,8.40,NaN,11.79,10.0 [8.4-11.8],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_adult_overweight_30_prepared.csv

**Описание содержимого:** распространенность ожирения среди взрослых, ИМТ >= 30 (стандартизированная по возрасту оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_adult_overweight_30.csv`.

In [127]:
who_bmi_adult_overweight_30_prepared_data = pd.read_csv(
    './data/who_bmi_adult_overweight_30_prepared.csv'
)

who_bmi_adult_overweight_30_prepared_data.head()

  SpatialDimValueCode  Period  BmiAdultOverweight30
0                 VNM    2020                  1.71
1                 ZMB    2020                 10.04
2                 IDN    2020                  9.98
3                 HTI    2020                 10.15
4                 FRA    2020                 10.07

## who_bmi_child_5_9_thinness.csv

**Описание содержимого:** распространенность худобы среди детей 5-9 лет, ИМТ < -2 стандартных отклонений ниже медианы (грубая оценка) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-thinness-among-children-and-adolescents-bmi--2-standard-deviations-below-the-median-(crude-estimate)-(-)

In [128]:
who_bmi_child_5_9_thinness_data = pd.read_csv(
    './data/who_bmi_child_5_9_thinness.csv'
)

who_bmi_child_5_9_thinness_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_MINUS2C,Prevalence of thinness among children and adol...,numeric,WPR,Western Pacific,Country,TON,Tonga,Year,2020,...,NaN,NaN,0.14,NaN,1.74,0.6 [0.1-1.7],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_MINUS2C,Prevalence of thinness among children and adol...,numeric,AMR,Americas,Country,CHL,Chile,Year,2020,...,NaN,NaN,0.28,NaN,1.90,0.8 [0.3-1.9],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_child_5_9_thinness_prepared.csv

**Описание содержимого:** распространенность худобы среди детей 5-9 лет, ИМТ < -2 стандартных отклонений ниже медианы (грубая оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_child_5_9_thinness.csv`.

In [129]:
who_bmi_child_5_9_thinness_prepared_data = pd.read_csv(
    './data/who_bmi_child_5_9_thinness_prepared.csv'
)

who_bmi_child_5_9_thinness_prepared_data.head()

  SpatialDimValueCode  Period  BmiChildThinness
0                 TON    2020              0.63
1                 CHL    2020              0.84
2                 NLD    2020              0.81
3                 URY    2020              0.84
4                 NZL    2020              0.84

## who_bmi_teenager_10_19_thinness.csv

**Описание содержимого:** распространенность худобы среди подростков 10-19 лет, ИМТ < -2 стандартных отклонений ниже медианы (грубая оценка) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-thinness-among-children-and-adolescents-bmi--2-standard-deviations-below-the-median-(crude-estimate)-(-)

In [130]:
who_bmi_teenager_10_19_thinness_data = pd.read_csv(
    './data/who_bmi_teenager_10_19_thinness.csv'
)

who_bmi_teenager_10_19_thinness_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_MINUS2C,Prevalence of thinness among children and adol...,numeric,WPR,Western Pacific,Country,TON,Tonga,Year,2020,...,NaN,NaN,0.16,NaN,0.71,0.4 [0.2-0.7],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_MINUS2C,Prevalence of thinness among children and adol...,numeric,WPR,Western Pacific,Country,NIU,Niue,Year,2020,...,NaN,NaN,0.17,NaN,1.48,0.6 [0.2-1.5],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_teenager_10_19_thinness_prepared.csv

**Описание содержимого:** распространенность худобы среди подростков 10-19 лет, ИМТ < -2 стандартных отклонений ниже медианы (грубая оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_teenager_10_19_thinness.csv`.

In [131]:
who_bmi_teenager_10_19_thinness_prepared_data = pd.read_csv(
    './data/who_bmi_teenager_10_19_thinness_prepared.csv'
)

who_bmi_teenager_10_19_thinness_prepared_data.head()

  SpatialDimValueCode  Period  BmiTeenagerThinness
0                 TON    2020                 0.36
1                 NIU    2020                 0.61
2                 NRU    2020                 0.69
3                 COK    2020                 0.67
4                 ASM    2020                 0.76

## who_bmi_child_5_9_overweight_1.csv

**Описание содержимого:** распространенность избыточного веса среди детей 5-9 лет, ИМТ > +1 стандартного отклонения выше медианы (грубая оценка) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-overweight-among-children-and-adolescents-bmi-1-standard-deviations-above-the-median-(crude-estimate)-(-)

In [132]:
who_bmi_child_5_9_overweight_1_data = pd.read_csv(
    './data/who_bmi_child_5_9_overweight_1.csv'
)

who_bmi_child_5_9_overweight_1_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_PLUS1C,Prevalence of overweight among children and ad...,numeric,AFR,Africa,Country,NGA,Nigeria,Year,2020,...,NaN,NaN,7.25,NaN,14.1,10.4 [7.2-14.1],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_PLUS1C,Prevalence of overweight among children and ad...,numeric,SEAR,South-East Asia,Country,IND,India,Year,2020,...,NaN,NaN,9.33,NaN,11.7,10.5 [9.3-11.7],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_child_5_9_overweight_1_prepared.csv

**Описание содержимого:** распространенность избыточного веса среди детей 5-9 лет, ИМТ > +1 стандартного отклонения выше медианы (грубая оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_child_5_9_overweight_1.csv`.

In [133]:
who_bmi_child_5_9_overweight_1_prepared_data = pd.read_csv(
    './data/who_bmi_child_5_9_overweight_1_prepared.csv'
)

who_bmi_child_5_9_overweight_1_prepared_data.head()

  SpatialDimValueCode  Period  BmiChildOverweight1
0                 NGA    2020                10.37
1                 IND    2020                10.47
2                 ZWE    2020                10.76
3                 NER    2020                11.07
4                 ERI    2020                11.19

## who_bmi_teenager_10_19_overweight_1.csv

**Описание содержимого:** распространенность избыточного веса среди подростков 10-19 лет, ИМТ > +1 стандартного отклонения выше медианы (грубая оценка) (%).
 
**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-overweight-among-children-and-adolescents-bmi-1-standard-deviations-above-the-median-(crude-estimate)-(-)

In [134]:
who_bmi_teenager_10_19_overweight_1_data = pd.read_csv(
    './data/who_bmi_teenager_10_19_overweight_1.csv'
)

who_bmi_teenager_10_19_overweight_1_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_PLUS1C,Prevalence of overweight among children and ad...,numeric,AFR,Africa,Country,COG,Congo,Year,2020,...,NaN,NaN,5.96,NaN,15.37,10.1 [6.0-15.4],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_PLUS1C,Prevalence of overweight among children and ad...,numeric,AFR,Africa,Country,GIN,Guinea,Year,2020,...,NaN,NaN,7.55,NaN,14.66,10.6 [7.5-14.7],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_teenager_10_19_overweight_1_prepared.csv

**Описание содержимого:** распространенность избыточного веса среди подростков 10-19 лет, ИМТ > +1 стандартного отклонения выше медианы (грубая оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_teenager_10_19_overweight_1.csv`.

In [135]:
who_bmi_teenager_10_19_overweight_1_prepared_data = pd.read_csv(
    './data/who_bmi_teenager_10_19_overweight_1_prepared.csv'
)

who_bmi_teenager_10_19_overweight_1_prepared_data.head()

  SpatialDimValueCode  Period  BmiTeenagerOverweight1
0                 COG    2020                   10.06
1                 GIN    2020                   10.59
2                 TGO    2020                   10.57
3                 GNB    2020                   10.83
4                 GMB    2020                   10.84

## who_bmi_child_5_9_overweight_2.csv

**Описание содержимого:** распространенность ожирения среди детей 5-9 лет, ИМТ > +2 стандартных отклонений выше медианы (грубая оценка) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-obesity-among-children-and-adolescents-bmi-2-standard-deviations-above-the-median-(crude-estimate)-(-)

In [136]:
who_bmi_child_5_9_overweight_2_data = pd.read_csv(
    './data/who_bmi_child_5_9_overweight_2.csv'
)

who_bmi_child_5_9_overweight_2_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_PLUS2C,Prevalence of obesity among children and adole...,numeric,AFR,Africa,Country,BFA,Burkina Faso,Year,2020,...,NaN,NaN,0.30,NaN,2.41,1.0 [0.3-2.4],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_PLUS2C,Prevalence of obesity among children and adole...,numeric,SEAR,South-East Asia,Country,TLS,Timor-Leste,Year,2020,...,NaN,NaN,0.37,NaN,2.13,1.0 [0.4-2.1],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_child_5_9_overweight_2_prepared.csv

**Описание содержимого:** распространенность ожирения среди детей 5-9 лет, ИМТ > +2 стандартных отклонений выше медианы (грубая оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_child_5_9_overweight_2.csv`.

In [137]:
who_bmi_child_5_9_overweight_2_prepared_data = pd.read_csv(
    './data/who_bmi_child_5_9_overweight_2_prepared.csv'
)

who_bmi_child_5_9_overweight_2_prepared_data.head()

  SpatialDimValueCode  Period  BmiChildOverweight2
0                 BFA    2020                 1.02
1                 TLS    2020                 1.02
2                 BGD    2020                 1.75
3                 TJK    2020                 1.72
4                 TZA    2020                 1.92

## who_bmi_teenager_10_19_overweight_2.csv

**Описание содержимого:** распространенность ожирения среди подростков 10-19 лет, ИМТ > +2 стандартных отклонений выше медианы (грубая оценка) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/prevalence-of-obesity-among-children-and-adolescents-bmi-2-standard-deviations-above-the-median-(crude-estimate)-(-)

In [138]:
who_bmi_teenager_10_19_overweight_2_data = pd.read_csv(
    './data/who_bmi_teenager_10_19_overweight_2.csv'
)

who_bmi_teenager_10_19_overweight_2_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,NCD_BMI_PLUS2C,Prevalence of obesity among children and adole...,numeric,SEAR,South-East Asia,Country,TLS,Timor-Leste,Year,2020,...,NaN,NaN,0.33,NaN,1.24,0.7 [0.3-1.2],NaN,NaN,EN,2024-02-28T21:00:00.000Z
1,NCD_BMI_PLUS2C,Prevalence of obesity among children and adole...,numeric,AFR,Africa,Country,ETH,Ethiopia,Year,2020,...,NaN,NaN,0.42,NaN,1.31,0.8 [0.4-1.3],NaN,NaN,EN,2024-02-28T21:00:00.000Z

## who_bmi_teenager_10_19_overweight_2_prepared.csv

**Описание содержимого:** распространенность ожирения среди подростков 10-19 лет, ИМТ > +2 стандартных отклонений выше медианы (грубая оценка) (%).

**Источник данных:** создана из таблицы `who_bmi_teenager_10_19_overweight_2.csv`.

In [139]:
who_bmi_teenager_10_19_overweight_2_prepared_data = pd.read_csv(
    './data/who_bmi_teenager_10_19_overweight_2_prepared.csv'
)

who_bmi_teenager_10_19_overweight_2_prepared_data.head()

  SpatialDimValueCode  Period  BmiTeenagerOverweight2
0                 TLS    2020                    0.70
1                 ETH    2020                    0.79
2                 BFA    2020                    0.86
3                 RWA    2020                    1.03
4                 MDG    2020                    1.22

## who_sanitation.csv

**Описание содержимого:** население, пользующееся как минимум базовыми услугами санитарии (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/population-using-at-least-basic-sanitation-services-(-)

In [140]:
who_sanitation_data = pd.read_csv(
    './data/who_sanitation.csv'
)

who_sanitation_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WSH_SANITATION_BASIC,Population using at least basic sanitation ser...,text,EUR,Europe,Country,AND,Andorra,Year,2020,...,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,EN,2023-07-09T21:00:00.000Z
1,WSH_SANITATION_BASIC,Population using at least basic sanitation ser...,text,WPR,Western Pacific,Country,AUS,Australia,Year,2020,...,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,EN,2023-07-09T21:00:00.000Z

## who_sanitation_prepared.csv

**Описание содержимого:** население, пользующееся как минимум базовыми услугами санитарии (%).

**Источник данных:** создана из таблицы `who_sanitation.csv`.

In [141]:
who_sanitation_prepared_data = pd.read_csv(
    './data/who_sanitation_prepared.csv'
)

who_sanitation_prepared_data.head()

  SpatialDimValueCode  Period  Sanitation
0                 AND    2020      100.00
1                 AUS    2020      100.00
2                 AUT    2020       99.97
3                 BHR    2020      100.00
4                 CHL    2020      100.00

## who_drinking_water.csv

**Описание содержимого:** население, пользующееся по крайней мере базовыми услугами питьевого водоснабжения (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/population-using-at-least-basic-drinking-water-services-(-)

In [142]:
who_drinking_water_data = pd.read_csv(
    './data/who_drinking_water.csv'
)

who_drinking_water_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,WSH_WATER_BASIC,Population using at least basic drinking-water...,text,EUR,Europe,Country,AND,Andorra,Year,2020,...,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,EN,2023-07-09T21:00:00.000Z
1,WSH_WATER_BASIC,Population using at least basic drinking-water...,text,EUR,Europe,Country,ARM,Armenia,Year,2020,...,NaN,NaN,NaN,NaN,NaN,100,NaN,NaN,EN,2023-07-09T21:00:00.000Z

## who_drinking_water_prepared.csv

**Описание содержимого:** население, пользующееся по крайней мере базовыми услугами питьевого водоснабжения (%).

**Источник данных:** создана из таблицы `who_drinking_water.csv`.

In [143]:
who_drinking_water_prepared_data = pd.read_csv(
    './data/who_drinking_water_prepared.csv'
)

who_drinking_water_prepared_data.head()

  SpatialDimValueCode  Period  DrinkingWater
0                 AND    2020         100.00
1                 ARM    2020          99.94
2                 AUS    2020          99.97
3                 AUT    2020         100.00
4                 BHR    2020          99.92

## who_health_care_costs.csv

**Описание содержимого:** общие внутренние государственные расходы на здравоохранение в процентах от общих государственных расходов (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/domestic-general-government-health-expenditure-(gghe-d)-as-percentage-of-general-government-expenditure-(gge)

In [144]:
who_health_care_costs_data = pd.read_csv(
    './data/who_health_care_costs.csv'
)

who_health_care_costs_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,GHED_GGHE-DGGE_SHA2011,Domestic general government health expenditure...,text,EMR,Eastern Mediterranean,Country,SYR,Syrian Arab Republic,Year,2020,...,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,EN,2024-12-09T21:00:00.000Z
1,GHED_GGHE-DGGE_SHA2011,Domestic general government health expenditure...,text,EUR,Europe,Country,KAZ,Kazakhstan,Year,2020,...,NaN,NaN,NaN,NaN,NaN,10.06,NaN,NaN,EN,2024-12-09T21:00:00.000Z

## who_health_care_costs_prepared.csv

**Описание содержимого:** общие внутренние государственные расходы на здравоохранение в процентах от общих государственных расходов (%).

**Источник данных:** создана из таблицы `who_health_care_costs.csv`.

In [145]:
who_health_care_costs_prepared_data = pd.read_csv(
    './data/who_health_care_costs_prepared.csv'
)

who_health_care_costs_prepared_data.head()

  SpatialDimValueCode  Period  HealthCareCosts
0                 SYR    2020            10.00
1                 KAZ    2020            10.06
2                 SYC    2020            10.18
3                 IDN    2020            10.24
4                 OMN    2020            10.24

## who_health_care_costs_gdp.csv

**Описание содержимого:** общие внутренние государственные расходы на здравоохранение в процентах от валового внутреннего продукта (ВВП) (%).

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/domestic-general-government-health-expenditure-(gghe-d)-as-percentage-of-gross-domestic-product-(gdp)-(-)

In [146]:
who_health_care_costs_gdp_data = pd.read_csv(
    './data/who_health_care_costs_gdp.csv'
)

who_health_care_costs_gdp_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,GHED_GGHE-DGDP_SHA2011,Domestic general government health expenditure...,numeric,EMR,Eastern Mediterranean,Country,SOM,Somalia,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.15,NaN,NaN,EN,2024-12-09T21:00:00.000Z
1,GHED_GGHE-DGDP_SHA2011,Domestic general government health expenditure...,numeric,EMR,Eastern Mediterranean,Country,YEM,Yemen,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.39,NaN,NaN,EN,2024-12-09T21:00:00.000Z

## who_health_care_costs_gdp_prepared.csv

**Описание содержимого:** общие внутренние государственные расходы на здравоохранение в процентах от валового внутреннего продукта (ВВП) (%).

**Источник данных:** создана из таблицы `who_health_care_costs_gdp.csv`

In [147]:
who_health_care_costs_gdp_prepared_data = pd.read_csv(
    './data/who_health_care_costs_gdp_prepared.csv'
)

who_health_care_costs_gdp_prepared_data.head()

  SpatialDimValueCode  Period  HealthCareCostsGdp
0                 SOM    2020                0.15
1                 YEM    2020                0.39
2                 BGD    2020                0.41
3                 HTI    2020                0.41
4                 NGA    2020                0.51

## who_health_care_costs_per_capita.csv

**Описание содержимого:** общие внутренние государственные расходы на здравоохранение на душу населения в долларах США.

**Источник данных:** https://www.who.int/data/gho/data/indicators/indicator-details/GHO/domestic-general-government-health-expenditure-(gghe-d)-per-capita-in-us

In [148]:
who_health_care_costs_per_capita_data = pd.read_csv(
    './data/who_health_care_costs_per_capita.csv'
)

who_health_care_costs_per_capita_data.head(2)

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,...,FactValueUoM,FactValueNumericLowPrefix,FactValueNumericLow,FactValueNumericHighPrefix,FactValueNumericHigh,Value,FactValueTranslationID,FactComments,Language,DateModified
0,GHED_GGHE-D_pc_US_SHA2011,Domestic general government health expenditure...,numeric,EMR,Eastern Mediterranean,Country,SOM,Somalia,Year,2020,...,NaN,NaN,NaN,NaN,NaN,0.83,NaN,NaN,EN,2024-12-09T21:00:00.000Z
1,GHED_GGHE-D_pc_US_SHA2011,Domestic general government health expenditure...,numeric,AFR,Africa,Country,NGA,Nigeria,Year,2020,...,NaN,NaN,NaN,NaN,NaN,10.16,NaN,NaN,EN,2024-12-09T21:00:00.000Z

## who_health_care_costs_per_capita_prepared.csv

**Описание содержимого:** общие внутренние государственные расходы на здравоохранение на душу населения в долларах США.

**Источник данных:** создана из таблицы `who_health_care_costs_per_capita.csv`.

In [149]:
who_health_care_costs_per_capita_prepared_data = pd.read_csv(
    './data/who_health_care_costs_per_capita_prepared.csv'
)

who_health_care_costs_per_capita_prepared_data.head()

  SpatialDimValueCode  Period  HealthCareCostsPerCapita
0                 SOM    2020                      0.83
1                 NGA    2020                     10.16
2                 UGA    2020                     10.17
3                 MMR    2020                     10.99
4                 NIC    2020                    102.60

## worldbank_gdp_per_capita.csv

**Описание содержимого:** ВВП на душу населения (в долл. США).

**Источник данных:** https://data.worldbank.org/indicator/NY.GDP.PCAP.CD?end=2020&most_recent_year_desc=true&start=2000

In [150]:
worldbank_gdp_per_capita_data = pd.read_csv(
    './data/worldbank_gdp_per_capita.csv'
)

worldbank_gdp_per_capita_data.head(2)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27458.225331,27441.529662,28440.051964,30082.127645,31096.205074,22855.932320,27200.061079,30559.533535,33984.79062,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.132432,186.947182,197.408105,225.447007,209.005786,226.883067,...,1479.564123,1329.777824,1520.171298,1538.924188,1493.780445,1344.080962,1522.590088,1628.024526,1659.51529,NaN

## worldbank_gdp_per_capita_prepared.csv

**Описание содержимого:** ВВП на душу населения (в долл. США).

**Источник данных:** создана из таблицы `worldbank_gdp_per_capita.csv`.

In [151]:
worldbank_gdp_per_capita_prepared_data = pd.read_csv(
    './data/worldbank_gdp_per_capita_prepared.csv'
)

worldbank_gdp_per_capita_prepared_data.head()

  SpatialDimValueCode  Period  GdpPerCapita
0                 AFG    2000    174.930991
1                 AGO    2000    563.733796
2                 ALB    2000   1126.683340
3                 ARE    2000  29865.502347
4                 ARG    2000   7637.014892

## worldbank_population.csv

**Описание содержимого:** общая численность населения страны.

**Источник данных:** https://data.worldbank.org/indicator/SP.POP.TOTL?end=2020&most_recent_year_desc=true&start=2000

In [152]:
worldbank_population_data = pd.read_csv(
    './data/worldbank_population.csv'
)

worldbank_population_data.head(2)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,Unnamed: 68
0,Aruba,ABW,"Population, total",SP.POP.TOTL,54922.0,55578.0,56320.0,57002.0,57619.0,58190.0,...,107906.0,108727.0,108735.0,108908.0,109203.0,108587.0,107700.0,107310.0,107359.0,NaN
1,Africa Eastern and Southern,AFE,"Population, total",SP.POP.TOTL,130072080.0,133534923.0,137171659.0,140945536.0,144904094.0,149033472.0,...,607123269.0,623369401.0,640058741.0,657801085.0,675950189.0,694446100.0,713090928.0,731821393.0,750503764.0,NaN

## worldbank_population_prepared.csv

**Описание содержимого:** общая численность населения страны.

**Источник данных:** создана из таблицы `worldbank_population.csv`.

In [153]:
worldbank_population_prepared_data = pd.read_csv(
    './data/worldbank_population_prepared.csv'
)

worldbank_population_prepared_data.head()

  SpatialDimValueCode  Period  Population
0                 AFG    2000  20130327.0
1                 AGO    2000  16194869.0
2                 ALB    2000   3089027.0
3                 ARE    2000   3493575.0
4                 ARG    2000  37213984.0

## ourworldindata_schooling.csv

**Описание содержимого:** средняя продолжительность формального образования для лиц в возрасте 15–64 лет.

**Источник данных:** https://ourworldindata.org/grapher/mean-years-of-schooling-long-run

> [Барро и Ли (2015)](http://www.barrolee.com/);
> [Ли и Ли (2016)](https://barrolee.github.io/BarroLeeDataSet/DataLeeLee.html) - 
> с обработкой [Our World In Data](https://ourworldindata.org/grapher/mean-years-of-schooling-long-run). \
> **Руководство по цитированию:** Пожалуйста, укажите все источники, перечисленные выше. \
> Данные, предоставленные  сторонними источниками через Our World in Data, \
> остаются подпадающими под условия лицензии исходных поставщиков.

In [154]:
ourworldindata_schooling_data = pd.read_csv(
    './data/ourworldindata_schooling.csv'
)

ourworldindata_schooling_data.head()

,Entity,Code,Year,Combined - average years of education for 15-64 years male and female youth and adults
0,Afghanistan,AFG,2000,3.03
1,Afghanistan,AFG,2005,3.32
2,Afghanistan,AFG,2010,3.93
3,Afghanistan,AFG,2015,4.81
4,Afghanistan,AFG,2020,5.69

## ourworldindata_schooling_prepared.csv

**Описание содержимого:** средняя продолжительность формального образования для лиц в возрасте 15–64 лет.

**Источник данных:** создана из таблицы `ourworldindata_schooling.csv`.

In [155]:
ourworldindata_schooling_prepared_data = pd.read_csv(
    './data/ourworldindata_schooling_prepared.csv'
)

ourworldindata_schooling_prepared_data.head()

  SpatialDimValueCode  Period  Schooling
0                 AFG    2000       3.03
1                 ALB    2000       9.93
2                 ARE    2000       9.35
3                 ARG    2000       9.08
4                 ARM    2000      10.45

---

## cumulative_life_expectancy.csv

**Описание содержимого:** итоговая таблица с данными о продолжительности жизни и факторами, на нее влияющими.

**Источник данных:** создана из перечисленных выше таблиц (преимущественно с окончаниями `_prepared`)

In [156]:
cumulative_life_expectancy_data = pd.read_csv(
    './data/cumulative_life_expectancy.csv'
)

cumulative_life_expectancy_data.head()

,ParentLocationCode,ParentLocation,SpatialDimValueCode,Location,Period,AdultMortality,Homicides,MaternalMortality,AdultNcdMortality,AdultNcdMortality117,...,BmiTeenagerOverweight2,Sanitation,DrinkingWater,HealthCareCosts,HealthCareCostsGdp,HealthCareCostsPerCapita,GdpPerCapita,Population,Schooling,LifeExpectancy
0,AFR,Africa,AGO,Angola,2000,345.6,13.31,859.92091,30.5,4555.0,...,0.99,27.56,41.14,2.74,1.11,7.66,563.733796,16194869.0,5.027188,49.37
1,AFR,Africa,AGO,Angola,2001,338.6,13.10,799.64079,29.7,4606.0,...,1.07,28.99,42.25,5.97,2.05,13.35,533.586202,16747208.0,5.092250,50.06
2,AFR,Africa,AGO,Angola,2002,325.1,12.88,758.27183,29.4,4687.0,...,1.14,30.42,43.38,4.19,1.31,11.54,882.147847,17327699.0,5.157312,51.06
3,AFR,Africa,AGO,Angola,2003,321.6,12.65,676.49647,29.3,4838.0,...,1.22,31.86,44.36,4.26,1.47,14.55,992.698979,17943712.0,5.222375,51.74
4,AFR,Africa,AGO,Angola,2004,322.4,12.29,594.19216,29.0,4892.0,...,1.31,33.29,45.35,5.66,1.69,21.36,1266.210864,18600423.0,5.287437,52.36

## cumulative_life_expectancy_prepared.csv

**Описание содержимого:** итоговая таблица с данными о продолжительности жизни и факторами, на нее влияющими.

**Источник данных:** cоздана из таблицы `cumulative_life_expectancy.csv` путем преобразования признаков (перевода в другой масштаб и пр.).

In [157]:
cumulative_life_expectancy_prepared_data = pd.read_csv(
    './data/cumulative_life_expectancy_prepared.csv'
)

cumulative_life_expectancy_prepared_data.head()

,ParentLocationCode,ParentLocation,SpatialDimValueCode,Location,Period,AdultMortality,Homicides,MaternalMortality,AdultNcdMortality,AdultNcdMortality117,...,BmiTeenagerOverweight2,Sanitation,DrinkingWater,HealthCareCosts,HealthCareCostsGdp,HealthCareCostsPerCapita,GdpPerCapita,Population,Schooling,LifeExpectancy
0,AFR,Africa,AGO,Angola,2000,34.56,0.01331,0.859921,30.5,0.028126,...,0.99,27.56,41.14,2.74,1.11,7.66,563.733796,16194869.0,5.027188,49.37
1,AFR,Africa,AGO,Angola,2001,33.86,0.01310,0.799641,29.7,0.027503,...,1.07,28.99,42.25,5.97,2.05,13.35,533.586202,16747208.0,5.092250,50.06
2,AFR,Africa,AGO,Angola,2002,32.51,0.01288,0.758272,29.4,0.027049,...,1.14,30.42,43.38,4.19,1.31,11.54,882.147847,17327699.0,5.157312,51.06
3,AFR,Africa,AGO,Angola,2003,32.16,0.01265,0.676496,29.3,0.026962,...,1.22,31.86,44.36,4.26,1.47,14.55,992.698979,17943712.0,5.222375,51.74
4,AFR,Africa,AGO,Angola,2004,32.24,0.01229,0.594192,29.0,0.026300,...,1.31,33.29,45.35,5.66,1.69,21.36,1266.210864,18600423.0,5.287437,52.36

## integration_order.csv

**Описание содержимого:** cодержит порядки интегрирования временных рядов ожидаемой продолжительности жизни для каждой страны.

**Источник данных:** cоздана из таблицы `cumulative_life_expectancy_prepared.csv`

In [3]:
integration_order_data = pd.read_csv(
    './data/integration_order.csv'
)

integration_order_data.head()

  SpatialDimValueCode  IntegrationOrder
0                 AGO                 2
1                 BDI                 1
2                 BEN                 0
3                 BFA                 4
4                 BWA                 1